version: '3.7'

networks:
  monitor-net:
    ipam:
      driver: default
      config:
      - subnet: 172.29.0.0/16

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /tmp/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - polkadot-exporter
    networks:
      monitor-net:
        ipv4_address: 172.29.1.2


  polkadot-exporter:
    image: mixbytes/polkadot-prometheus-exporter
    command: 
      - "--exporter_port=9090" 
    ports:
      - 9091:9090
    networks:
      monitor-net:
        ipv4_address: 172.29.1.3


  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - /tmp/monitoring/provisioning/:/etc/grafana/provisioning/
    networks:
      monitor-net:
        ipv4_address: 172.29.1.4
    user: "104"

