global:
  evaluation_interval: 1m
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
- job_name: node_alice
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: 172.29.1.3:9090
    target_label: __address__
  static_configs:
  - targets:
    - 172.28.1.1:9933
- job_name: node_bob
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: 172.29.1.3:9090
    target_label: __address__
  static_configs:
  - targets:
    - 172.28.1.2:9935
