{
 "title": "Polkadot metrics",
 "description": "Grafana dashboard compatible with all the polkadot and substrate based blockchains.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time to finality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_block_finality_seconds_sum[5m]) / rate(polkadot_block_finality_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Best block",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "max(polkadot_best_block)" }
   ]
  },
  {
   "title": "Best finalized",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "max(polkadot_best_finalized)" }
   ]
  },
  {
   "title": "Average block production time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_block_production_seconds_sum[5m]) / rate(polkadot_block_production_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Average block propagation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(polkadot_block_propagation_seconds_sum[1m]) / irate(polkadot_block_propagation_seconds_count[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}